# Plot difference between An, Rd, fe, gs_opt, ci, cs

In [1]:
import xarray as xr
import matplotlib.pyplot as plt
import numpy as np

In [2]:
results_high = xr.open_dataset('../results/testrun_test_june.nc')

In [3]:
results_mid = xr.open_dataset('../results/testrun_base_june.nc')

In [4]:
target_variables = ['pt_net_co2_sunlit','pt_net_co2_shaded',
                    'pt_dark_respiration_sunlit', 'pt_dark_respiration_shaded',
                    'pt_stomatal_conductance_h2o_sunlit','pt_stomatal_conductance_h2o_shaded',
                    'pt_transpiration_sunlit','pt_transpiration_shaded',
                    'pt_leaf_internal_co2_sunlit','pt_leaf_internal_co2_shaded',
                    'pt_leaf_surface_co2_sunlit','pt_leaf_surface_co2_shaded','canopy_lad',
                    'pt_boundary_conductance_h2o_sunlit','pt_boundary_conductance_h2o_shaded',
                    'ffloor_surface_temperature','gt_temperature',
                    'canopy_SWnet','canopy_leaf_net_SW']

In [5]:
difference = np.abs(results_high[target_variables] - results_mid[target_variables])/results_high[target_variables]*100

In [6]:
for key, value in difference.items():
    distribution = value.values.flatten()
    print(key)
    print(np.nanmin(distribution), np.nanmean(distribution), np.nanmedian(distribution), np.nanmax(distribution))

results_high.close()
results_mid.close()

pt_net_co2_sunlit
-0.0009693352 5.1031326e-05 1.5858395e-05 0.0039703
pt_net_co2_shaded
-1.5914142 3.9398774e-06 7.550355e-06 1.432046
pt_dark_respiration_sunlit
0.0 0.00012134626 5.544283e-05 0.0027885267
pt_dark_respiration_shaded
0.0 2.7642262e-05 9.569042e-06 0.0009771562
pt_stomatal_conductance_h2o_sunlit
0.0 0.00010108043 1.9401003e-05 0.005232058
pt_stomatal_conductance_h2o_shaded
0.0 5.5009878e-05 7.912142e-06 0.0052249255
pt_transpiration_sunlit
0.0 0.0035289668 0.0029178686 0.026545197
pt_transpiration_shaded
0.0 0.00087574887 0.0004475934 0.007905317
pt_leaf_internal_co2_sunlit
0.0 8.270449e-05 6.9663045e-05 0.0015906382
pt_leaf_internal_co2_shaded
0.0 1.4409455e-05 0.0 0.00068848155
pt_leaf_surface_co2_sunlit
0.0 5.3245487e-05 5.2640582e-05 0.0013881185
pt_leaf_surface_co2_shaded
0.0 7.805174e-06 0.0 0.00031552088
canopy_lad
0.0 0.0 0.0 0.0
pt_boundary_conductance_h2o_sunlit
0.050479144 0.14381015 0.14508605 0.27563685
pt_boundary_conductance_h2o_shaded
0.05106869 0.1467841

In [ ]:
m = 10
c = np.zeros(shape=(2*m+2))
c[1:2*(m):2] = 5
c[2:2*m+1:2] = 7
c

array([0., 5., 7., 5., 7., 5., 7., 5., 7., 5., 7., 5., 7., 5., 7., 5., 7.,
       5., 7., 5., 7., 0.])

In [14]:
for i in range(1,2*(m),2):
    print(i)

1
3
5
7
9
11
13
15
17
19


In [ ]:
diag = np.zeros(2*m+2)
subdiag = np.zeros(2*m+1)
superdiag = np.zeros(2*m+1)

diag[1:2*(m):2] = 
diag[]

In [26]:

n = 5
d0  = np.array([4, 4, 4, 4, 4], dtype=float)     # main diagonal
d1  = np.array([0,1, 1, 1, 1], dtype=float)        # superdiagonal
dm1 = np.array([2, 2, 2, 2,0], dtype=float)        # subdiagonal

# # Build dense matrix
# A_dense = (
#     np.diag(d0,  k=0) +
#     np.diag(d1,  k=1) +
#     np.diag(dm1, k=-1)
# )

# print(A_dense)
# [[4. 1. 0. 0. 0.]
#  [2. 4. 1. 0. 0.]
#  [0. 2. 4. 1. 0.]
#  [0. 0. 2. 4. 1.]
#  [0. 0. 0. 2. 4.]]


In [27]:
np.vstack((d1, d0, dm1))

array([[0., 1., 1., 1., 1.],
       [4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 0.]])