# Plot difference between An, Rd, fe, gs_opt, ci, cs

In [28]:
import xarray as xr
import matplotlib.pyplot as plt
import numpy as np

In [29]:
results_high = xr.open_dataset('../results/FiHy2018_profiling_1em2_crit.nc')

In [30]:
results_mid = xr.open_dataset('../results/FiHy2018_profiling_sanity_check_photo_c_maxiter.nc')

In [31]:
target_variables = ['pt_net_co2_sunlit','pt_net_co2_shaded',
                    'pt_dark_respiration_sunlit', 'pt_dark_respiration_shaded',
                    'pt_stomatal_conductance_h2o_sunlit','pt_stomatal_conductance_h2o_shaded',
                    'pt_transpiration_sunlit','pt_transpiration_shaded',
                    'pt_leaf_internal_co2_sunlit','pt_leaf_internal_co2_shaded',
                    'pt_leaf_surface_co2_sunlit','pt_leaf_surface_co2_shaded','canopy_lad',
                    'pt_boundary_conductance_h2o_sunlit','pt_boundary_conductance_h2o_shaded',
                    'ffloor_surface_temperature','gt_temperature',
                    'canopy_SWnet','canopy_leaf_net_SW']

In [32]:
difference = np.abs(results_high[target_variables] - results_mid[target_variables])/results_high[target_variables]*100

In [33]:
for key, value in difference.items():
    distribution = value.values.flatten()
    print(key)
    print(np.nanmin(distribution), np.nanmean(distribution), np.nanmedian(distribution), np.nanmax(distribution))

results_high.close()
results_mid.close()

pt_net_co2_sunlit
-0.6135097 0.00081976206 0.00037452654 2.2008116
pt_net_co2_shaded
-152.92845 0.0017653832 7.138095e-05 170.3941
pt_dark_respiration_sunlit
0.0 0.0011770525 0.000484509 0.054696407
pt_dark_respiration_shaded
0.0 0.0012566004 0.0004912341 0.055244554
pt_stomatal_conductance_h2o_sunlit
0.0 0.0013199756 0.00056965643 0.09528748
pt_stomatal_conductance_h2o_shaded
0.0 0.0013027947 0.00015008771 0.076657444
pt_transpiration_sunlit
0.0 0.004933035 0.0037301048 0.10080312
pt_transpiration_shaded
0.0 0.0030873856 0.0013753084 0.100799985
pt_leaf_internal_co2_sunlit
0.0 0.00023860054 9.6126954e-05 0.020359674
pt_leaf_internal_co2_shaded
0.0 0.00015850003 2.9872303e-05 0.018319348
pt_leaf_surface_co2_sunlit
0.0 8.783963e-05 6.0214756e-05 0.008791507
pt_leaf_surface_co2_shaded
0.0 4.392199e-05 1.4967904e-05 0.0026204675
canopy_lad
0.0 0.0 0.0 0.0
pt_boundary_conductance_h2o_sunlit
0.0057773707 0.144105 0.14512436 1.2694036
pt_boundary_conductance_h2o_shaded
0.0023562596 0.1478513

In [34]:
m = 10
c = np.zeros(shape=(2*m+2))
c[1:2*(m):2] = 5
c[2:2*m+1:2] = 7
c

array([0., 5., 7., 5., 7., 5., 7., 5., 7., 5., 7., 5., 7., 5., 7., 5., 7.,
       5., 7., 5., 7., 0.])

In [35]:
for i in range(1,2*(m),2):
    print(i)

1
3
5
7
9
11
13
15
17
19


In [36]:
diag = np.zeros(2*m+2)
subdiag = np.zeros(2*m+1)
superdiag = np.zeros(2*m+1)

diag[1:2*(m):2] = 
diag[]

SyntaxError: invalid syntax (4095518677.py, line 5)

In [ ]:

n = 5
d0  = np.array([4, 4, 4, 4, 4], dtype=float)     # main diagonal
d1  = np.array([0,1, 1, 1, 1], dtype=float)        # superdiagonal
dm1 = np.array([2, 2, 2, 2,0], dtype=float)        # subdiagonal

# # Build dense matrix
# A_dense = (
#     np.diag(d0,  k=0) +
#     np.diag(d1,  k=1) +
#     np.diag(dm1, k=-1)
# )

# print(A_dense)
# [[4. 1. 0. 0. 0.]
#  [2. 4. 1. 0. 0.]
#  [0. 2. 4. 1. 0.]
#  [0. 0. 2. 4. 1.]
#  [0. 0. 0. 2. 4.]]


In [ ]:
np.vstack((d1, d0, dm1))

array([[0., 1., 1., 1., 1.],
       [4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 0.]])